server:
  port: 8989
spring:
  cloud:
    nacos:
      server-addr: 101.34.65.221:8848
    gateway:
      routes:
        - id: user_route
          uri: lb://USERS
          predicates:
            - Path=/user
        - id: product_route
          uri: lb://PRODUCTIONS
          predicates:
            - Path=/products
  application:
    name: GATEWAY
